### PR TITLE
Split storage into separate package

### PR DESCRIPTION
**Pull request by mgravell**
WIP

### CODE REVIEW

**Comment by badrishc** [comment]
we would really prefer to avoid NS2.0 like the plague going forward. its a huge burden to carry forward. do we have some very strong reasons to want it back?

**Comment by mgravell** [comment]
@badrishc I'm very aware of the pain (https://blog.marcgravell.com/2020/01/net-core-net-5-exodus-of-net-framework.html); in my head, I was also thinking of how often I still see legacy .NET Framework in use, both in public and inside MSFT. I can see both angles here, but if it isn't going to be mergeable, I won't waste the effort 👍

**Comment by badrishc** [comment]
The split into a separate storage nuget is still interesting/useful and orthogonal to NS2.0, right?

I agree with your points. If we need NS2.0 for some known production use case, we could be fine with adding it, but maybe we could let someone ask for it first.

**Comment by mgravell** [comment]
@badrishc yes, but I'll take a look at how the packaging was done for FASTER. I'm usually a fan of csproj, but I seem to recall here using manual nuspec instead

**Pull request closed without merging**
